### ISSUE TITLE
Pausing then playing a Music assistant entity through home assistant restarts the song instead of resuming from where you left off.

### ISSUE THREAD

**Issue by ironcrafter54** [music-assistant/python-hass-client#217]
Pausing then playing a Music assistant entity through home assistant restarts the song instead of resuming from where you left off. I am running the latest version of music assistant as of now, and my songs are from the spotify integration. My player is a snapcast client connected to music assistant's built in snapserver.

**Comment by marcelveldt** [comment]
please dont create issue reports here for Music Assistant but post them on one of the music assistant support channels github issue tracker or discord). Thanks!
